In [1]:
import numpy as np

In [13]:
X = np.random.uniform(-1,1, size=(2,4,4))
print(X)

[[[-0.14276141 -0.00527125  0.0771284  -0.70219174]
  [ 0.60262087  0.91520695  0.44399787 -0.43525742]
  [ 0.64639082  0.65744268  0.84789291  0.1401115 ]
  [-0.37368607 -0.01554186 -0.98678487  0.10339816]]

 [[ 0.78058096  0.25642068  0.72773769  0.46129048]
  [-0.67341891 -0.0587437  -0.11326865 -0.06869009]
  [-0.15859801 -0.17702731  0.65095821 -0.04657511]
  [ 0.28182958  0.52384463 -0.11897385  0.99509818]]]


In [14]:
def baseline_2(x_valid):
    rt = 0.9
    x_valid[x_valid<0] = 0
    x_save = x_valid.copy()
    x_valid = x_valid.reshape(-1, x_valid.shape[1]*x_valid.shape[2])
    evo_diff_cummass_rt = np.sort(x_valid, axis=1).cumsum(axis=1) - rt * np.sum(
        x_valid, axis=1
    ).reshape(-1, 1)
    N_drop_val = (
        np.where(evo_diff_cummass_rt < 0, evo_diff_cummass_rt, -np.inf).argmin(
            axis=1
        )
    )
    x_valid[
        x_valid.argsort(axis=1).argsort(axis=1) < N_drop_val.reshape(-1, 1)
    ] = 0
    pred_baseline_2 = x_valid.reshape(-1, x_save.shape[1], x_save.shape[2])
    pred_baseline_2[pred_baseline_2>0] = 1
    return pred_baseline_2

baseline_2(X)

array([[[0., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 1.]]])

In [50]:
evo_diff_cummass_rt

array([[-8.09473399, -8.02557216, -7.83330812, -7.56449789, -7.26268239,
        -6.90052201, -6.46512968, -5.78849703, -5.01157318, -4.21314362,
        -3.41209242, -2.59440215, -1.75063016, -0.90029021, -0.04515572,
         0.90460182],
       [-6.78006373, -6.73923906, -6.61874399, -6.31671967, -6.01335729,
        -5.5597973 , -5.08660913, -4.59890479, -4.0892032 , -3.56929723,
        -2.96720349, -2.31929398, -1.6204062 , -0.85927253, -0.07158817,
         0.75422574]])